version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: evaluation-service-api:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=evaluation
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  worker-text:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: evaluation-service-worker:latest
    restart: unless-stopped
    command: ["node", "dist/workers/textEvaluation.worker.js"]
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=evaluation_service
    depends_on:
      - mongo
      - redis

  worker-audio:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: evaluation-service-worker:latest
    restart: unless-stopped
    command: ["node", "dist/workers/audioEvaluation.worker.js"]
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=evaluation
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
