name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --silent

      - name: Unit tests
        run: npm test --silent

      - name: Build
        run: npm run build --silent

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          tags: local/evaluation-service-api:ci
          push: false

      - name: Build Worker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.worker
          tags: local/evaluation-service-worker:ci
          push: false
